# -*- coding: utf-8 -*-
"""mail_spam_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5FjAv4dFcwCPUaVBHph44ahrG6lR-KE
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm

spam = pd.read_csv('mail_data.csv')

z = spam['Message']
y = spam["Category"]
z_train, z_test,y_train, y_test = train_test_split(z,y,test_size = 0.2)

cv = CountVectorizer()
features = cv.fit_transform(z_train)

model = svm.SVC()
model.fit(features,y_train)

features_test = cv.transform(z_test)
print("Accuracy: {}".format(model.score(features_test,y_test)))

